name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole ^
            --name "GNNImageResize" ^
            --hidden-import PIL._tkinter_finder ^
            gnn_image_resize.py
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GNNImageResize
          path: dist/GNNImageResize.exe
